ProductTag:
    type: entity
    table: product_tag
    indexes:
        new_key_421874593660532:
            columns:
                - tag_id
    id: {  }
    oneToOne:
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        tag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
